### ISSUE TITLE
Angularjs google direction throws error googleDirections.getDirections is not a function

### ISSUE THREAD

**Issue by Pinsonbavard** [dbaq/angularjs-google-directions#3] opened 2015-04-28 19:06 UTC
I tried using this dependency to get all Google direction from a start address to a destination but it throws this error, please help resolve this.

**Comment by dbaq** [comment] 2015-04-28 19:07
can you give some code please?

**Comment by Pinsonbavard** [comment] 2015-04-29 04:50
var starter = angular.module('starter', ['starter.controllers', 'dbaq.google.directions']);

starter .controller('HomeController', function($scope, googleDirections) {
  var args = {
    origin: '37.7738571,-122.4102823',
    destination: '37.7891231,-122.4173545',
    travelMode: 'driving'
  }

  $scope.directions = googleDirections.getDirections(args).then(function(directions) {
    return directions;
  });
});

It throws the following errors

// ReferenceError Google is undefined
// It throws an error googleDirections.getDirections is not a function

**Comment by Pinsonbavard** [comment] 2015-04-29 05:52
Moreso, If I do not add .service('googleDirections', function () { /* ... */ }) to the starter above, It throws the following error 

![google-direction-error](https://cloud.githubusercontent.com/assets/6134716/7385350/3e45b2e0-ee3c-11e4-806a-c07b4ca92888.PNG)
![add-service](https://cloud.githubusercontent.com/assets/6134716/7385355/5305a032-ee3c-11e4-933e-4a3c5cf50c9c.PNG)

**Comment by Pinsonbavard** [comment] 2015-04-29 19:09
This is the js file for the angular-google-directions

/*! angularjs-google-directions 11-08-2014 */
"use strict";

angular.module("dbaq.google.directions",[]),
angular.module("dbaq.google.directions").value("googleMaps",google.maps),
angular.module("dbaq.google.directions").provider("googleDirections",function(){var a={unitSystem:null,durationInTraffic:!1,waypoints:[],optimizeWaypoints:!1,provideRouteAlternatives:!1,avoidHighways:!1,avoidTolls:!1};
	this.$get=function(b,c,d,e){function f(f){function g(a,c){b.$apply(c==d.DirectionsStatus.OK||c==d.DirectionsStatus.ZERO_RESULTS?function(){return k.resolve(a)}:function(){return k.reject(c)})}
	var h=angular.copy(a,{});angular.extend(h,f);
	var i,j,k=c.defer();return i=h.map?h.map:h.elem?h.elem:e.document.createElement("div"),j=new d.DirectionsService,j.route(h,g),k.promise}
	var g=[];g.driving=d.TravelMode.DRIVING,g.bicycling=d.TravelMode.BICYCLING,g.transit=d.TravelMode.TRANSIT,g.walking=d.TravelMode.WALKING;
	var h=[];return h.metric=d.UnitSystem.METRIC,h.imperial=d.UnitSystem.IMPERIAL,{getDirections:function(a){return a.travelMode=g[a.travelMode]||d.TravelMode.DRIVING,a.unitSystem=h[a.unitSystem]||d.UnitSystem.IMPERIAL,f(a)}}},this.$get.$inject=["$rootScope","$q","googleMaps","$window"]});

**Comment by dbaq** [comment] 2015-04-30 17:15
hey @Pinsonbavard,

make sure to include the google library before all the other JS files, see ```Usage``` section in the Readme.md
```Include the Google Maps JS library in your app```

```<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=true"></script>

**Comment by Pinsonbavard** [comment] 2015-05-01 05:59
![include](https://cloud.githubusercontent.com/assets/6134716/7427275/97d049b2-efcf-11e4-962e-9cfb73ad9df4.PNG)

I have included it.

**Comment by Pinsonbavard** [comment] 2015-05-01 06:36
The problem still persist even after including the google maps library. I checked the angular-google-direction js, the getDirections function within it is probably not seen by the googleDirections, Or?

**Comment by Pinsonbavard** [comment] 2015-05-01 06:41
If I console.log(googleDirections) It shows an empty object but adding the getDirections method throws the error "googleDirections.getDirections" is not a function.

**Comment by Pinsonbavard** [comment] 2015-05-01 06:44
I just realized the problem occurs when I add the "args"  parameters, I mean
console.log(googleDirections.getDirections(args))

**Comment by Pinsonbavard** [comment] 2015-05-01 08:43
Without putting the getDirections() as function, it does not throw any error

**Comment by dbaq** [comment] 2015-05-01 16:27
In your code, you included:
```<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=true"></script>```
could you please try to include this one:
```<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=true"></script>```

**Comment by Pinsonbavard** [comment] 2015-05-01 20:16
![ref-google](https://cloud.githubusercontent.com/assets/6134716/7436620/42dbf0b4-f047-11e4-96c7-724dc6b9c82e.PNG)

![ref-error](https://cloud.githubusercontent.com/assets/6134716/7436446/b65f73dc-f045-11e4-8bc7-922a98606e1f.PNG)

**Comment by Pinsonbavard** [comment] 2015-05-01 20:20
I added &amp; to <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=true"></script> to make it 

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&amp;sensor=true"></script> and it loads google correctly by returning an object. But the error still persist

**Comment by dbaq** [comment] 2015-05-01 20:37
Please use http://plnkr.co/ to post your code and reproduce the error so I can help you.

**Comment by Pinsonbavard** [comment] 2015-05-01 20:38
![script-ref](https://cloud.githubusercontent.com/assets/6134716/7436931/590a2f6a-f04a-11e4-9ab6-97d1b6321957.PNG)

**Comment by Pinsonbavard** [comment] 2015-05-01 20:38
Okay

**Comment by Pinsonbavard** [comment] 2015-05-01 22:01
I don't know why Plunker is not saving my work.. It is saying saved failed.

**Comment by Pinsonbavard** [comment] 2015-05-01 22:04
Index


<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
    <script src="angular-google-direction.js"></script>
    <script src="http://code.angularjs.org/1.2.0-rc.2/angular.js"></script>
  </head>

  <body>
    <h1>Hello Plunker!</h1>
    <div>{{ directions || "Please work..."}}</div>
  </body>

</html>

**Comment by Pinsonbavard** [comment] 2015-05-01 22:05
Script


// Code goes here

var TrafficJam = angular.module('TrafficJam.controllers', ['dbaq.google.directions']).service('googleDirections',function(){})

.controller('homeController', ['$scope','$rootScope','ROUTE_SERVICE', '$q', 'USER_LOCATION','googleDirections', function($scope,$rootScope,ROUTE_SERVICE,$q,USER_LOCATION,googleDirections){

    

    

    var getMyLocation = function(){ 


         // my_services($rootScope.current_location,'somolu');      

          
                    var args = {
            origin: 'Yaba colle of technology',
            destination: 'Somolu',
            travelMode: 'driving'
          }

          $scope.directions = googleDirections.getDirections(args).then(function(directions) {
            return directions;
          });

  
    }
    
    getMyLocation();


 

}])

**Comment by Pinsonbavard** [comment] 2015-05-01 22:05
Angular-google-direction




/*! angularjs-google-directions 11-08-2014 */

"use strict";angular.module("dbaq.google.directions",[]),angular.module("dbaq.google.directions").value("googleMaps",google.maps),angular.module("dbaq.google.directions").provider("googleDirections",function(){var a={unitSystem:null,durationInTraffic:!1,waypoints:[],optimizeWaypoints:!1,provideRouteAlternatives:!1,avoidHighways:!1,avoidTolls:!1};this.$get=function(b,c,d,e){function f(f){function g(a,c){b.$apply(c==d.DirectionsStatus.OK||c==d.DirectionsStatus.ZERO_RESULTS?function(){return k.resolve(a)}:function(){return k.reject(c)})}var h=angular.copy(a,{});angular.extend(h,f);var i,j,k=c.defer();return i=h.map?h.map:h.elem?h.elem:e.document.createElement("div"),j=new d.DirectionsService,j.route(h,g),k.promise}var g=[];g.driving=d.TravelMode.DRIVING,g.bicycling=d.TravelMode.BICYCLING,g.transit=d.TravelMode.TRANSIT,g.walking=d.TravelMode.WALKING;var h=[];return h.metric=d.UnitSystem.METRIC,h.imperial=d.UnitSystem.IMPERIAL,{getDirections:function(a){return a.travelMode=g[a.travelMode]||d.TravelMode.DRIVING,a.unitSystem=h[a.unitSystem]||d.UnitSystem.IMPERIAL,f(a)}}},this.$get.$inject=["$rootScope","$q","googleMaps","$window"]});

**Comment by dbaq** [comment] 2015-05-01 22:07
Please stop posting code like that, it is not readable at all.

if you can't use plunkr to reproduce your issue, you have alternatives like https://jsfiddle.net/.

**Comment by Pinsonbavard** [comment] 2015-05-02 15:48
https://jsfiddle.net/hv4d5qbp/

**Comment by dbaq** [comment] 2015-05-03 17:05
Your JSFiddle is not working at all. I can't reproduce your issue (since it is not working).

Please see docs.jsfiddle.net/tutorial.html to find out how it works.

Post again here when you're sure that I will be able to reproduce the issue. Thanks.

**Comment by Pinsonbavard** [comment] 2015-05-12 01:12
Hello Didier, the plugin is now working but it is only returning just one object which is origin and destination, but how can I get object for instructions such as turn left to "ABC" street and the likes. 

Thanks

**Comment by Pinsonbavard** [comment] 2015-05-12 01:24
See the result

**Comment by Pinsonbavard** [comment] 2015-05-12 01:24
Directions Search Example

{"routes":[{"bounds":{"Ea":{"A":6.517220000000001,"j":6.51897},"wa":{"j":3.38241,"A":3.39101}},"copyrights":"Map data ©2015 Google","legs":[{"distance":{"text":"0.7 mi","value":1059},"duration":{"text":"3 mins","value":185},"end_address":"Yaba, Lagos, Nigeria","end_location":{"A":6.5177933,"F":3.3824156000000585},"start_address":"Dan Fodio Boulevard, Lagos, Nigeria","start_location":{"A":6.5189678,"F":3.391012000000046},"steps":[{"distance":{"text":"0.5 mi","value":743},"duration":{"text":"2 mins","value":114},"end_location":{"A":6.5177448,"F":3.38470499999994},"polyline":{"points":"qfxf@yhuSHh@Jf@Rh@j@`At@lAb@v@Pb@Rf@b@pAHb@Jf@^vBJ|@@vAKxAStBM~@CJQp@GLAL?TDp@"},"start_location":{"A":6.5189678,"F":3.391012000000046},"travel_mode":"DRIVING","encoded_lat_lngs":"qfxf@yhuSHh@Jf@Rh@j@`At@lAb@v@Pb@Rf@b@pAHb@Jf@^vBJ|@@vAKxAStBM~@CJQp@GLAL?TDp@","path":[{"A":6.51897,"F":3.39101},{"A":6.5189200000000005,"F":3.3908000000000005},{"A":6.51886,"F":3.3906},{"A":6.51876,"F":3.3903900000000005},{"A":6.518540000000001,"F":3.39006},{"A":6.51827,"F":3.38967},{"A":6.518090000000001,"F":3.38939},{"A":6.518000000000001,"F":3.3892100000000003},{"A":6.517900000000001,"F":3.3890100000000003},{"A":6.517720000000001,"F":3.3886000000000003},{"A":6.517670000000001,"F":3.3884200000000004},{"A":6.51761,"F":3.3882200000000005},{"A":6.51745,"F":3.38762},{"A":6.517390000000001,"F":3.3873100000000003},{"A":6.51738,"F":3.3868700000000005},{"A":6.517440000000001,"F":3.38642},{"A":6.51754,"F":3.3858300000000003},{"A":6.51761,"F":3.3855100000000005},{"A":6.5176300000000005,"F":3.38545},{"A":6.517720000000001,"F":3.3852},{"A":6.517760000000001,"F":3.38513},{"A":6.5177700000000005,"F":3.38506},{"A":6.5177700000000005,"F":3.3849500000000003},{"A":6.517740000000001,"F":3.3847000000000005}],"lat_lngs":[{"A":6.51897,"F":3.39101},{"A":6.5189200000000005,"F":3.3908000000000005},{"A":6.51886,"F":3.3906},{"A":6.51876,"F":3.3903900000000005},{"A":6.518540000000001,"F":3.39006},{"A":6.51827,"F":3.38967},{"A":6.518090000000001,"F":3.38939},{"A":6.518000000000001,"F":3.3892100000000003},{"A":6.517900000000001,"F":3.3890100000000003},{"A":6.517720000000001,"F":3.3886000000000003},{"A":6.517670000000001,"F":3.3884200000000004},{"A":6.51761,"F":3.3882200000000005},{"A":6.51745,"F":3.38762},{"A":6.517390000000001,"F":3.3873100000000003},{"A":6.51738,"F":3.3868700000000005},{"A":6.517440000000001,"F":3.38642},{"A":6.51754,"F":3.3858300000000003},{"A":6.51761,"F":3.3855100000000005},{"A":6.5176300000000005,"F":3.38545},{"A":6.517720000000001,"F":3.3852},{"A":6.517760000000001,"F":3.38513},{"A":6.5177700000000005,"F":3.38506},{"A":6.5177700000000005,"F":3.3849500000000003},{"A":6.517740000000001,"F":3.3847000000000005}],"instructions":"Head <b>west</b> on <b>Dan Fodio Blvd/University Rd</b> towards <b>Access link</b><div style=\"font-size:0.9em\">Pass by Unilag Central Mosque (on the right)</div>","maneuver":"","start_point":{"A":6.5189678,"F":3.391012000000046},"end_point":{"A":6.5177448,"F":3.38470499999994}},{"distance":{"text":"0.2 mi","value":252},"duration":{"text":"1 min","value":61},"end_location":{"A":6.517221699999999,"F":3.3824869000000035},"polyline":{"points":"{~wf@katS?D?D?B@L@H?DRfAh@`DNp@JpA@FFT"},"start_location":{"A":6.5177448,"F":3.38470499999994},"travel_mode":"DRIVING","encoded_lat_lngs":"{~wf@katS?D?D?B@L@H?DRfAh@`DNp@JpA@FFT","path":[{"A":6.517740000000001,"F":3.3847000000000005},{"A":6.517740000000001,"F":3.3846700000000003},{"A":6.517740000000001,"F":3.38464},{"A":6.517740000000001,"F":3.3846200000000004},{"A":6.51773,"F":3.3845500000000004},{"A":6.517720000000001,"F":3.3845},{"A":6.517720000000001,"F":3.3844700000000003},{"A":6.517620000000001,"F":3.38411},{"A":6.517410000000001,"F":3.3833},{"A":6.51733,"F":3.3830500000000003},{"A":6.517270000000001,"F":3.3826400000000003},{"A":6.51726,"F":3.3826000000000005},{"A":6.517220000000001,"F":3.38249}],"lat_lngs":[{"A":6.517740000000001,"F":3.3847000000000005},{"A":6.517740000000001,"F":3.3846700000000003},{"A":6.517740000000001,"F":3.38464},{"A":6.517740000000001,"F":3.3846200000000004},{"A":6.51773,"F":3.3845500000000004},{"A":6.517720000000001,"F":3.3845},{"A":6.517720000000001,"F":3.3844700000000003},{"A":6.517620000000001,"F":3.38411},{"A":6.517410000000001,"F":3.3833},{"A":6.51733,"F":3.3830500000000003},{"A":6.517270000000001,"F":3.3826400000000003},{"A":6.51726,"F":3.3826000000000005},{"A":6.517220000000001,"F":3.38249}],"instructions":"Continue onto <b>University Rd</b><div style=\"font-size:0.9em\">Pass by Brotherhood Of The Cross And Star (on the left)</div>","maneuver":"","start_point":{"A":6.5177448,"F":3.38470499999994},"end_point":{"A":6.517221699999999,"F":3.3824869000000035}},{"distance":{"text":"210 ft","value":64},"duration":{"text":"1 min","value":10},"end_location":{"A":6.5177933,"F":3.3824156000000585},"maneuver":"turn-right","polyline":{"points":"s{wf@qssSiANg@A"},"start_location":{"A":6.517221699999999,"F":3.3824869000000035},"travel_mode":"DRIVING","encoded_lat_lngs":"s{wf@qssSiANg@A","path":[{"A":6.517220000000001,"F":3.38249},{"A":6.51759,"F":3.38241},{"A":6.517790000000001,"F":3.38242}],"lat_lngs":[{"A":6.517220000000001,"F":3.38249},{"A":6.51759,"F":3.38241},{"A":6.517790000000001,"F":3.38242}],"instructions":"Turn <b>right</b> at VitaFoam onto <b>Davies St</b><div style=\"font-size:0.9em\">Destination will be on the right</div>","start_point":{"A":6.517221699999999,"F":3.3824869000000035},"end_point":{"A":6.5177933,"F":3.3824156000000585}}],"via_waypoint":[],"via_waypoints":[]}],"overview_polyline":"qfxf@yhuSTpARh@j@`AxAdCd@jAb@pAHb@j@~CJ|@@vAKxAStBQjAY~@Ab@Dv@B`@lA`HLxAFTiANg@A","summary":"Dan Fodio Blvd/University Rd","warnings":[],"waypoint_order":[],"overview_path":[{"A":6.51897,"F":3.39101},{"A":6.51886,"F":3.3906},{"A":6.51876,"F":3.3903900000000005},{"A":6.518540000000001,"F":3.39006},{"A":6.518090000000001,"F":3.38939},{"A":6.517900000000001,"F":3.3890100000000003},{"A":6.517720000000001,"F":3.3886000000000003},{"A":6.517670000000001,"F":3.3884200000000004},{"A":6.51745,"F":3.38762},{"A":6.517390000000001,"F":3.3873100000000003},{"A":6.51738,"F":3.3868700000000005},{"A":6.517440000000001,"F":3.38642},{"A":6.51754,"F":3.3858300000000003},{"A":6.5176300000000005,"F":3.38545},{"A":6.517760000000001,"F":3.38513},{"A":6.5177700000000005,"F":3.3849500000000003},{"A":6.517740000000001,"F":3.3846700000000003},{"A":6.517720000000001,"F":3.3845},{"A":6.51733,"F":3.3830500000000003},{"A":6.51726,"F":3.3826000000000005},{"A":6.517220000000001,"F":3.38249},{"A":6.51759,"F":3.38241},{"A":6.517790000000001,"F":3.38242}]}],"status":"OK","request":{"unitSystem":1,"durationInTraffic":false,"waypoints":[],"optimizeWaypoints":false,"provideRouteAlternatives":false,"avoidHighways":false,"avoidTolls":false,"origin":"Dan Fodio Boulevard, Lagos, Nigeria","destination":"Yaba,Lagos,Nigeria","travelMode":"DRIVING"}}

**Comment by dbaq** [comment] 2015-05-12 01:31
You got the "instructions" in the response ..

"instructions":"Head west on Dan Fodio Blvd/University Rd towards Access link Pass by Unilag Central Mosque (on the right)"
"instructions":"Continue onto University Rd Pass by Brotherhood Of The Cross And Star (on the left)"
"instructions":"Turn right at VitaFoam onto Davies St Destination will be on the right"


I am closing since issue since you made it work. Since you are working with the google api, you should read that page: https://developers.google.com/maps/documentation/api-picker

**Closed by dbaq** 2015-05-12 01:31 UTC

**Comment by Pinsonbavard** [comment] 2015-05-12 02:16
I want to get data such as University Rd, Davies Street
